{% raw %}
name: CI
on: [push, pull_request]

jobs:
  gnu-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment (Linux)
      if: contains(matrix.os, 'ubuntu')
      run: |
        echo "ROOTFOLDER=${PWD}" >> $GITHUB_ENV
        echo "FC=gfortran" >> $GITHUB_ENV
        echo "CC=gcc" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install cmake ninja-build

    - name: Set up environment (OSX)
      if: contains(matrix.os, 'macos')
      run: |
        echo "ROOTFOLDER=${PWD}" >> $GITHUB_ENV
        echo "FC=gfortran-9" >> $GITHUB_ENV
        echo "CC=gcc-9" >> $GITHUB_ENV
        brew install ninja

    - name: Configure build
      run: >-
        cmake -B _build -G Ninja
        -DCMAKE_INSTALL_PREFIX=${PWD}/_install

    - name: Build project
      run: |
        cmake --build _build

    - name: Install project
      run: |
        cmake --install _build

    - name: Run tests
      run: |
        cd _build
        ctest -j 2 --output-on-failure
        cd -

    - name: Install project
      run: |
        cmake --install _build

    - name: Run integration test
      run: |
        mkdir integtest
        CMAKE_PREFIX_PATH=${ROOTFOLDER}/_install cmake -G Ninja ${ROOTFOLDER}/test/integration
        ninja
        ./test_build
{% endraw %}
